CREATE TABLE IF NOT EXISTS PRODUCT_ENTITY (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  precio DOUBLE NOT NULL,
  cantidad INT NOT NULL
);